adding text image 100
KwickerHub/frontend pull request #1029
Opened 2023-12-04 20:53 UTC by JasmineDavidson94

Created a new file and completed text on image 100. Thank you

2023-12-07 05:44 UTC, NtemKenyor commented
This is a great work you have done. However, U have also sent to this project hidden files. Please check your PC and remove the hidden files(Files that start with a dot). Please do just that and I would merger your PR immediately. thank you.

2023-12-07 05:48 UTC, NtemKenyor requested changes
remove hidden files created by your PC.

2023-12-10 01:31 UTC, JasmineDavidson94 commented
Apologies for the delay, I did not realize the PR hadn't been accepted. Thank you for the feedback! I have tried making the changes but cannot locate those hidden files. Any suggestions on how to resolve this issue.

2023-12-10 02:40 UTC, JasmineDavidson94 commented
I have created a new branch and deleted the requested files there. A new pull request was made. If this fixes the issue I can close this request

2023-12-14 11:05 UTC, NtemKenyor reviewed
Great Job n and check the possible changes.

2023-12-14 11:05 UTC, NtemKenyor commented on modules/text_on_image/text_on_image_100_Jasmine_Davidson.html
> +    <img src="https://images01.nicepagecdn.com/page/55/71/html-template-5571820.jpg" alt="Background Image">
You used the link of the image you were suppose to design.

2023-12-14 11:33 UTC, NtemKenyor commented on modules/text_on_image/text_on_image_100_Jasmine_Davidson.html
> +    <img src="https://images01.nicepagecdn.com/page/55/71/html-template-5571820.jpg" alt="Background Image">
your background image is really not a background image as it contains other text and write up...

2023-12-15 14:47 UTC, NtemKenyor approved these changes
Congratulations 👏

I would handle any other corrections myself. Thank you for contributing to Open Source development.

2023-12-15 14:47 UTC, merged