Added grid layout as per project requirements
KwickerHub/frontend pull request #1040
Opened 2023-12-12 23:50 UTC by LRKROSHAN

2023-12-13 10:41 UTC, krushnarout requested changes

2023-12-13 10:41 UTC, krushnarout commented on modules/grids/grid_299_Roshankumar.html
> +    <img src="images_and_icons/299.png" alt="Center Image" class="center-image">
@LRKROSHAN Where is `299.png` ? Add your image!

2023-12-15 06:42 UTC, LRKROSHAN reviewed
Hi I have added 299.png to modules/grids/images_and_icons

2023-12-15 06:58 UTC, krushnarout approved these changes
Looks good to me, Thanks for contributing.

2023-12-15 06:58 UTC, merged