Create Something_button.html
KwickerHub/frontend pull request #190
Opened 2023-04-16 01:20 UTC by Rakesh-116

2023-04-16 17:53 UTC, NtemKenyor requested changes

2023-04-16 17:53 UTC, NtemKenyor commented on modules/buttons/Something_button.html
> +            <img src="https://res.cloudinary.com/dbcowhqno/image/upload/v1681525774/DPzTPPKeBxFpdAVnKxIg_-transformed-removebg-preview_crqt3h.png" style="height:25px;width:25px;"/>Danger
what if this sever/url goes down some day? Let's build a powerful and highly efficient system. Use svg for the icon. check recent buttons.

2023-04-16 19:25 UTC, closed without merging

2023-04-16 19:28 UTC, Rakesh-116 commented
Hey I have changed the code according to your request, Check it out

On Sun, 16 Apr 2023 at 23:23, N. K. K. ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In modules/buttons/Something_button.html
> <https://github.com/KwickerHub/frontend/pull/190#discussion_r1167987529>:
>
> > +</head>
> +<body>
> +    <style>
> +      .danger-button{
> +        background-color:red;
> +        padding:10px;
> +        border-width: 0;
> +        border-radius:5px;
> +        color:#ffffff;
> +        font-weight:500;
> +        font-size:30px;
> +      }
> +    </style>
> +    <div>
> +        <button class="danger-button">
> +            <img src="https://res.cloudinary.com/dbcowhqno/image/upload/v1681525774/DPzTPPKeBxFpdAVnKxIg_-transformed-removebg-preview_crqt3h.png" style="height:25px;width:25px;"/>Danger
>
> what if this sever/url goes down some day? Let's build a powerful and
> highly efficient system. Use svg for the icon. check recent buttons.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KwickerHub/frontend/pull/190#pullrequestreview-1387008412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4QTZUIH763DGYWGTQ4SPB3XBQW2LANCNFSM6AAAAAAW7YWWTU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-17 04:24 UTC, Rakesh-116 commented
First of all sorry, I have done 6 more projects which are not assigned to
me, actually really did'nt know about it, sorry for that

On Mon, 17 Apr 2023 at 00:58, Rakesh Penugonda ***@***.***>
wrote:

> Hey I have changed the code according to your request, Check it out
>
> On Sun, 16 Apr 2023 at 23:23, N. K. K. ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In modules/buttons/Something_button.html
>> <https://github.com/KwickerHub/frontend/pull/190#discussion_r1167987529>:
>>
>> > +</head>
>> +<body>
>> +    <style>
>> +      .danger-button{
>> +        background-color:red;
>> +        padding:10px;
>> +        border-width: 0;
>> +        border-radius:5px;
>> +        color:#ffffff;
>> +        font-weight:500;
>> +        font-size:30px;
>> +      }
>> +    </style>
>> +    <div>
>> +        <button class="danger-button">
>> +            <img src="https://res.cloudinary.com/dbcowhqno/image/upload/v1681525774/DPzTPPKeBxFpdAVnKxIg_-transformed-removebg-preview_crqt3h.png" style="height:25px;width:25px;"/>Danger
>>
>> what if this sever/url goes down some day? Let's build a powerful and
>> highly efficient system. Use svg for the icon. check recent buttons.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/KwickerHub/frontend/pull/190#pullrequestreview-1387008412>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A4QTZUIH763DGYWGTQ4SPB3XBQW2LANCNFSM6AAAAAAW7YWWTU>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-04-17 09:08 UTC, NtemKenyor commented
you don't really need to apologize for that. I see it like an extra desire
to improve/learn....

I like your spirit.😊

On Mon, Apr 17, 2023, 05:25 Rakesh Penugonda ***@***.***>
wrote:

> First of all sorry, I have done 6 more projects which are not assigned to
> me, actually really did'nt know about it, sorry for that
>
> On Mon, 17 Apr 2023 at 00:58, Rakesh Penugonda ***@***.***>
> wrote:
>
> > Hey I have changed the code according to your request, Check it out
> >
> > On Sun, 16 Apr 2023 at 23:23, N. K. K. ***@***.***> wrote:
> >
> >> ***@***.**** requested changes on this pull request.
> >> ------------------------------
> >>
> >> In modules/buttons/Something_button.html
> >> <https://github.com/KwickerHub/frontend/pull/190#discussion_r1167987529
> >:
> >>
> >> > +</head>
> >> +<body>
> >> + <style>
> >> + .danger-button{
> >> + background-color:red;
> >> + padding:10px;
> >> + border-width: 0;
> >> + border-radius:5px;
> >> + color:#ffffff;
> >> + font-weight:500;
> >> + font-size:30px;
> >> + }
> >> + </style>
> >> + <div>
> >> + <button class="danger-button">
> >> + <img src="
> https://res.cloudinary.com/dbcowhqno/image/upload/v1681525774/DPzTPPKeBxFpdAVnKxIg_-transformed-removebg-preview_crqt3h.png"
> style="height:25px;width:25px;"/>Danger
> >>
> >> what if this sever/url goes down some day? Let's build a powerful and
> >> highly efficient system. Use svg for the icon. check recent buttons.
> >>
> >> —
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/KwickerHub/frontend/pull/190#pullrequestreview-1387008412
> >,
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/A4QTZUIH763DGYWGTQ4SPB3XBQW2LANCNFSM6AAAAAAW7YWWTU
> >
> >> .
> >> You are receiving this because you authored the thread.Message ID:
> >> ***@***.***>
> >>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KwickerHub/frontend/pull/190#issuecomment-1510677324>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOKWIBJ6NJT4HQDR5NPUDW3XBTA2FANCNFSM6AAAAAAW7YWWTU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-04-17 09:10 UTC, NtemKenyor commented
However, I would advise that you focus on one issue and get your PR
accepted before you solve others.

It's easier that way...

On Mon, Apr 17, 2023, 10:08 Kenyor Ntem ***@***.***> wrote:

> you don't really need to apologize for that. I see it like an extra desire
> to improve/learn....
>
> I like your spirit.😊
>
> On Mon, Apr 17, 2023, 05:25 Rakesh Penugonda ***@***.***>
> wrote:
>
>> First of all sorry, I have done 6 more projects which are not assigned to
>> me, actually really did'nt know about it, sorry for that
>>
>> On Mon, 17 Apr 2023 at 00:58, Rakesh Penugonda ***@***.***>
>> wrote:
>>
>> > Hey I have changed the code according to your request, Check it out
>> >
>> > On Sun, 16 Apr 2023 at 23:23, N. K. K. ***@***.***> wrote:
>> >
>> >> ***@***.**** requested changes on this pull request.
>> >> ------------------------------
>> >>
>> >> In modules/buttons/Something_button.html
>> >> <
>> https://github.com/KwickerHub/frontend/pull/190#discussion_r1167987529>:
>> >>
>> >> > +</head>
>> >> +<body>
>> >> + <style>
>> >> + .danger-button{
>> >> + background-color:red;
>> >> + padding:10px;
>> >> + border-width: 0;
>> >> + border-radius:5px;
>> >> + color:#ffffff;
>> >> + font-weight:500;
>> >> + font-size:30px;
>> >> + }
>> >> + </style>
>> >> + <div>
>> >> + <button class="danger-button">
>> >> + <img src="
>> https://res.cloudinary.com/dbcowhqno/image/upload/v1681525774/DPzTPPKeBxFpdAVnKxIg_-transformed-removebg-preview_crqt3h.png"
>> style="height:25px;width:25px;"/>Danger
>> >>
>> >> what if this sever/url goes down some day? Let's build a powerful and
>> >> highly efficient system. Use svg for the icon. check recent buttons.
>> >>
>> >> —
>> >> Reply to this email directly, view it on GitHub
>> >> <
>> https://github.com/KwickerHub/frontend/pull/190#pullrequestreview-1387008412
>> >,
>> >> or unsubscribe
>> >> <
>> https://github.com/notifications/unsubscribe-auth/A4QTZUIH763DGYWGTQ4SPB3XBQW2LANCNFSM6AAAAAAW7YWWTU
>> >
>> >> .
>> >> You are receiving this because you authored the thread.Message ID:
>> >> ***@***.***>
>> >>
>> >
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/KwickerHub/frontend/pull/190#issuecomment-1510677324>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOKWIBJ6NJT4HQDR5NPUDW3XBTA2FANCNFSM6AAAAAAW7YWWTU>
>> .
>> You are receiving this because you commented.Message ID:
>> ***@***.***>
>>
>

2023-04-17 09:21 UTC, Rakesh-116 commented
will you accept my pull requests

On Mon, 17 Apr 2023 at 14:40, N. K. K. ***@***.***> wrote:

> However, I would advise that you focus on one issue and get your PR
> accepted before you solve others.
>
> It's easier that way...
>
> On Mon, Apr 17, 2023, 10:08 Kenyor Ntem ***@***.***> wrote:
>
> > you don't really need to apologize for that. I see it like an extra
> desire
> > to improve/learn....
> >
> > I like your spirit.😊
> >
> > On Mon, Apr 17, 2023, 05:25 Rakesh Penugonda ***@***.***>
> > wrote:
> >
> >> First of all sorry, I have done 6 more projects which are not assigned
> to
> >> me, actually really did'nt know about it, sorry for that
> >>
> >> On Mon, 17 Apr 2023 at 00:58, Rakesh Penugonda ***@***.***>
> >> wrote:
> >>
> >> > Hey I have changed the code according to your request, Check it out
> >> >
> >> > On Sun, 16 Apr 2023 at 23:23, N. K. K. ***@***.***> wrote:
> >> >
> >> >> ***@***.**** requested changes on this pull request.
> >> >> ------------------------------
> >> >>
> >> >> In modules/buttons/Something_button.html
> >> >> <
> >> https://github.com/KwickerHub/frontend/pull/190#discussion_r1167987529
> >:
> >> >>
> >> >> > +</head>
> >> >> +<body>
> >> >> + <style>
> >> >> + .danger-button{
> >> >> + background-color:red;
> >> >> + padding:10px;
> >> >> + border-width: 0;
> >> >> + border-radius:5px;
> >> >> + color:#ffffff;
> >> >> + font-weight:500;
> >> >> + font-size:30px;
> >> >> + }
> >> >> + </style>
> >> >> + <div>
> >> >> + <button class="danger-button">
> >> >> + <img src="
> >>
> https://res.cloudinary.com/dbcowhqno/image/upload/v1681525774/DPzTPPKeBxFpdAVnKxIg_-transformed-removebg-preview_crqt3h.png
> "
> >> style="height:25px;width:25px;"/>Danger
> >> >>
> >> >> what if this sever/url goes down some day? Let's build a powerful and
> >> >> highly efficient system. Use svg for the icon. check recent buttons.
> >> >>
> >> >> —
> >> >> Reply to this email directly, view it on GitHub
> >> >> <
> >>
> https://github.com/KwickerHub/frontend/pull/190#pullrequestreview-1387008412
> >> >,
> >> >> or unsubscribe
> >> >> <
> >>
> https://github.com/notifications/unsubscribe-auth/A4QTZUIH763DGYWGTQ4SPB3XBQW2LANCNFSM6AAAAAAW7YWWTU
> >> >
> >> >> .
> >> >> You are receiving this because you authored the thread.Message ID:
> >> >> ***@***.***>
> >> >>
> >> >
> >>
> >> —
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/KwickerHub/frontend/pull/190#issuecomment-1510677324>,
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/AOKWIBJ6NJT4HQDR5NPUDW3XBTA2FANCNFSM6AAAAAAW7YWWTU
> >
> >> .
> >> You are receiving this because you commented.Message ID:
> >> ***@***.***>
> >>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KwickerHub/frontend/pull/190#issuecomment-1510981733>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4QTZULDBNUK7FKTPMRWTP3XBUCITANCNFSM6AAAAAAW7YWWTU>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>