fixing issue:- table Creator - Web design #32 #383
KwickerHub/frontend pull request #390
Opened 2023-10-01 10:48 UTC by Pranavnk15

As per the isuue created a pricing table template provided, 
Below is the ss of the same
![image](https://github.com/KwickerHub/frontend/assets/96475101/3943340c-98bf-4c93-a1d0-f9cb4f702ab6)

Hope, it is as per your consideration,
Would request you to accept it under the hacktoberfest, and marker under the label of hacktoerfest-accepted.

Thanks

2023-10-02 10:27 UTC, NtemKenyor requested changes
Thank you and Congratulations

Notwithstanding, Please make the changes and U can submit as many resolved issues as possible.

2023-10-02 10:27 UTC, NtemKenyor commented on modules/tables/table_NUM_Pranavnk15.html
> +        table {
Use precise class names so that your module does not affect another module or outer elements using this tag.

2023-10-02 15:05 UTC, Pranavnk15 reviewed
have changed the id and the name of the file , from table_NUM_Pranavnk15.html to table_32_Pranavnk15.html

2023-10-02 15:05 UTC, Pranavnk15 commented on modules/tables/table_NUM_Pranavnk15.html
> +        table {
should i change the name of the id ?
or anything else,
please elaborate in detail

2023-10-03 13:48 UTC, Pranavnk15 commented
hi @NtemKenyor please go through the revised changes, and accept the PR

2023-10-15 18:02 UTC, NtemKenyor approved these changes
Subject: 🚀 Appreciation for Your Patience and Outstanding Contribution! 🚀

Hello 👋

I hope this message finds you well. I wanted to take a moment to express my sincere gratitude for your incredible contribution to our project through your recent pull request. Your dedication and expertise shine brightly, and your input has made our project even better!

I also want to extend a heartfelt apology for the delay in my response. Balancing my passion for coding and open-source development with the demands of my job has been quite challenging recently. Your patience means the world to me, and I genuinely appreciate your understanding.

Your commitment to this project is inspiring, and I am so grateful to have you as part of our community. Your PR not only strengthens our codebase but also motivates me to overcome these challenges and keep pushing forward.

Thank you once again for your understanding and for being an essential part of our project. Your contributions are invaluable, and I am looking forward to seeing more amazing work from you in the future.

Warm regards,

2023-10-15 18:03 UTC, merged